unit BasicConstants;

interface

const
   // Voxel Map Fill Mode
   C_MODE_NONE = 0;
   C_MODE_ALL = 1;
   C_MODE_USED = 2;
   C_MODE_COLOUR = 3;
   C_MODE_NORMAL = 4;

   // Pixel position in the volume.
   C_OUTSIDE_VOLUME = 0;
   C_ONE_AXIS_INFLUENCE = 1;
   C_TWO_AXIS_INFLUENCE = 2;
   C_THREE_AXIS_INFLUENCE = 3;
   C_SEMI_SURFACE = 3;
   C_SURFACE = 4;
   C_INSIDE_VOLUME = 5;

   // Semi-surfaces configuration
   C_SF_BOTTOM_FRONT_LEFT_POINT = 1;
   C_SF_BOTTOM_FRONT_RIGHT_POINT = 2;
   C_SF_BOTTOM_BACK_LEFT_POINT = 4;
   C_SF_BOTTOM_BACK_RIGHT_POINT = 8;
   C_SF_TOP_FRONT_LEFT_POINT = $10;
   C_SF_TOP_FRONT_RIGHT_POINT = $20;
   C_SF_TOP_BACK_LEFT_POINT = $40;
   C_SF_TOP_BACK_RIGHT_POINT = $80;
   C_SF_BOTTOM_FRONT_LINE = $103;
   C_SF_BOTTOM_BACK_LINE = $20C;
   C_SF_BOTTOM_LEFT_LINE = $405;
   C_SF_BOTTOM_RIGHT_LINE = $80A;
   C_SF_TOP_FRONT_LINE = $1030;
   C_SF_TOP_BACK_LINE = $20C0;
   C_SF_TOP_LEFT_LINE = $4050;
   C_SF_TOP_RIGHT_LINE = $80A0;
   C_SF_LEFT_FRONT_LINE = $10011;
   C_SF_LEFT_BACK_LINE = $20044;
   C_SF_RIGHT_FRONT_LINE = $40022;
   C_SF_RIGHT_BACK_LINE = $80088;


implementation

end.
