program vxlse_III;

{$SetPEFlags $0020}


{%File 'source\Global_Conditionals.inc'}

uses
  Forms,
  FormHeaderUnit in 'source\forms\FormHeaderUnit.pas' {FrmHeader},
  FormReplaceColour in 'source\forms\FormReplaceColour.pas' {FrmReplaceColour},
  FormVoxelTexture in 'source\forms\FormVoxelTexture.pas' {FrmVoxelTexture},
  FormImportSection in 'source\forms\FormImportSection.pas' {FrmImportSection},
  FormFullResize in 'source\forms\FormFullResize.pas' {FrmFullResize},
  FormPreferences in 'source\forms\FormPreferences.pas' {FrmPreferences},
  FormVxlError in 'source\forms\FormVxlError.pas' {FrmVxlError},
  LoadForm in 'source\forms\LoadForm.pas' {LoadFrm},
  FormBoundsMAnager in 'source\forms\FormBoundsMAnager.pas' {FrmBoundsManager},
  FormNewSectionSizeUnit in 'source\forms\FormNewSectionSizeUnit.pas' {FrmNewSectionSize},
  FormNewVxlUnit in 'source\forms\FormNewVxlUnit.pas' {FrmNew},
  Form3dPreview in 'source\forms\Form3dPreview.pas' {Frm3DPReview},
  FormAutoNormals in 'source\forms\FormAutoNormals.pas' {FrmAutoNormals},
  FormPalettePackAbout in 'source\forms\FormPalettePackAbout.pas' {FrmPalettePackAbout},
  FormMain in 'source\forms\FormMain.pas' {FrmMain},
  Form3dModelizer in 'source\forms\Form3dModelizer.pas' {Frm3DModelizer},
  FormOptimizeMesh in 'source\forms\FormOptimizeMesh.pas' {FrmOptimizeMesh},
  FormRepairAssistant in 'source\forms\FormRepairAssistant.pas' {FrmRepairAssistant},
  FormGenerateDiffuseTexture in 'source\forms\FormGenerateDiffuseTexture.pas' {FrmGenerateDiffuseTexture},
  FormHeightmap in 'source\forms\FormHeightmap.pas' {FrmHeightMap},
  FormBumpMapping in 'source\forms\FormBumpMapping.pas' {FrmBumpMapping},
  FormTopologyAnalysis in 'source\forms\FormTopologyAnalysis.pas' {FrmTopologyAnalysis},
  MultiVector in 'source\maths\geometric_algebra\MultiVector.pas',
  EigenValues in 'source\maths\geometric_algebra\EigenValues.pas',
  GABasicFunctions in 'source\maths\geometric_algebra\GABasicFunctions.pas',
  GAConstants in 'source\maths\geometric_algebra\GAConstants.pas',
  GADataTypes in 'source\maths\geometric_algebra\GADataTypes.pas',
  GeometricAlgebra in 'source\maths\geometric_algebra\GeometricAlgebra.pas',
  Metric in 'source\maths\geometric_algebra\Metric.pas',
  BasicDataTypes in 'source\datatypes\BasicDataTypes.pas',
  AbstractDataSet in 'source\datatypes\simple\AbstractDataSet.pas',
  Abstract2DImageData in 'source\datatypes\simple\Abstract2DImageData.pas',
  Abstract3DVolumeData in 'source\datatypes\simple\Abstract3DVolumeData.pas',
  GlobalVars in 'source\constants\GlobalVars.pas',
  GLConstants in 'source\constants\GLConstants.pas',
  ByteDataSet in 'source\datatypes\simple\ByteDataSet.pas',
  BooleanDataSet in 'source\datatypes\simple\BooleanDataSet.pas',
  BasicConstants in 'source\constants\BasicConstants.pas',
  Constants in 'source\constants\Constants.pas',
  ImageGreyLongData in 'source\datatypes\simple\ImageGreyLongData.pas',
  ImageGreyByteData in 'source\datatypes\simple\ImageGreyByteData.pas',
  ImageGreyData in 'source\datatypes\simple\ImageGreyData.pas',
  ImageGreyIntData in 'source\datatypes\simple\ImageGreyIntData.pas',
  ImageRGBALongData in 'source\datatypes\simple\ImageRGBALongData.pas',
  ImageRGBAByteData in 'source\datatypes\simple\ImageRGBAByteData.pas',
  ImageRGBAData in 'source\datatypes\simple\ImageRGBAData.pas',
  ImageRGBAIntData in 'source\datatypes\simple\ImageRGBAIntData.pas',
  IntDataSet in 'source\datatypes\simple\IntDataSet.pas',
  ImageRGBByteData in 'source\datatypes\simple\ImageRGBByteData.pas',
  ImageRGBData in 'source\datatypes\simple\ImageRGBData.pas',
  ImageRGBIntData in 'source\datatypes\simple\ImageRGBIntData.pas',
  ImageRGBLongData in 'source\datatypes\simple\ImageRGBLongData.pas',
  Geometry in 'source\maths\Geometry.pas',
  LongDataSet in 'source\datatypes\simple\LongDataSet.pas',
  math3d in 'source\maths\math3d.pas',
  SingleDataSet in 'source\datatypes\simple\SingleDataSet.pas',
  RGBAByteDataSet in 'source\datatypes\simple\RGBAByteDataSet.pas',
  RGBAIntDataSet in 'source\datatypes\simple\RGBAIntDataSet.pas',
  RGBALongDataSet in 'source\datatypes\simple\RGBALongDataSet.pas',
  RGBASingleDataSet in 'source\datatypes\simple\RGBASingleDataSet.pas',
  RGBByteDataSet in 'source\datatypes\simple\RGBByteDataSet.pas',
  RGBIntDataSet in 'source\datatypes\simple\RGBIntDataSet.pas',
  RGBLongDataSet in 'source\datatypes\simple\RGBLongDataSet.pas',
  RGBSingleDataSet in 'source\datatypes\simple\RGBSingleDataSet.pas',
  VolumeGreyLongData in 'source\datatypes\simple\VolumeGreyLongData.pas',
  VolumeGreyByteData in 'source\datatypes\simple\VolumeGreyByteData.pas',
  VolumeGreyData in 'source\datatypes\simple\VolumeGreyData.pas',
  VolumeGreyIntData in 'source\datatypes\simple\VolumeGreyIntData.pas',
  VolumeRGBLongData in 'source\datatypes\simple\VolumeRGBLongData.pas',
  VolumeRGBAByteData in 'source\datatypes\simple\VolumeRGBAByteData.pas',
  VolumeRGBAData in 'source\datatypes\simple\VolumeRGBAData.pas',
  VolumeRGBAIntData in 'source\datatypes\simple\VolumeRGBAIntData.pas',
  VolumeRGBALongData in 'source\datatypes\simple\VolumeRGBALongData.pas',
  VolumeRGBByteData in 'source\datatypes\simple\VolumeRGBByteData.pas',
  VolumeRGBData in 'source\datatypes\simple\VolumeRGBData.pas',
  VolumeRGBIntData in 'source\datatypes\simple\VolumeRGBIntData.pas',
  ThreeDPointsDetector in 'source\datatypes\advanced\ThreeDPointsDetector.pas',
  TwoDPointOrderList in 'source\datatypes\advanced\TwoDPointOrderList.pas',
  TwoDPointQueue in 'source\datatypes\advanced\TwoDPointQueue.pas',
  ThreeDPointList in 'source\datatypes\advanced\ThreeDPointList.pas',
  FaceQueue in 'source\datatypes\advanced\FaceQueue.pas',
  BaseSet in 'source\datatypes\advanced\BaseSet.pas',
  IntegerSet in 'source\datatypes\advanced\IntegerSet.pas',
  IntegerList in 'source\datatypes\advanced\IntegerList.pas',
  QuadList in 'source\datatypes\advanced\QuadList.pas',
  VertexQueue in 'source\datatypes\advanced\VertexQueue.pas',
  TriangleList in 'source\datatypes\advanced\TriangleList.pas',
  TriangleNeighbourSet in 'source\datatypes\advanced\TriangleNeighbourSet.pas',
  Vector3fSet in 'source\datatypes\advanced\Vector3fSet.pas',
  VertexList in 'source\datatypes\advanced\VertexList.pas',
  BZK2_Sector in 'source\filetypes\bzk2\BZK2_Sector.pas',
  BZK2_Actor in 'source\filetypes\bzk2\BZK2_Actor.pas',
  BZK2_Camera in 'source\filetypes\bzk2\BZK2_Camera.pas',
  BZK2_File in 'source\filetypes\bzk2\BZK2_File.pas',
  BmpToDIB in 'source\filetypes\images\BmpToDIB.pas',
  DDS in 'source\filetypes\images\DDS.pas',
  pngimage in 'source\filetypes\images\pngimage.pas',
  PCXCtrl in 'source\filetypes\images\PCXCtrl.pas',
  pngzlib in 'source\filetypes\images\pngzlib.pas',
  pnglang in 'source\filetypes\images\pnglang.pas',
  TARGA in 'source\filetypes\images\TARGA.pas',
  PLYFile in 'source\filetypes\3dmodels\PLYFile.pas',
  ColladaFile in 'source\filetypes\3dmodels\ColladaFile.pas',
  ThreeDSFile in 'source\filetypes\3dmodels\ThreeDSFile.pas',
  OBJFile in 'source\filetypes\3dmodels\OBJFile.pas',
  Camera in 'source\rendering\Camera.pas',
  Actor in 'source\rendering\Actor.pas',
  IsoSurfaceFile in 'source\filetypes\3dmodels\IsoSurfaceFile.pas',
  VoxelView in 'source\rendering\VoxelView.pas',
  TextureBank in 'source\rendering\TextureBank.pas',
  TextureBankItem in 'source\rendering\TextureBankItem.pas',
  ShaderBankItem in 'source\rendering\ShaderBankItem.pas',
  Render in 'source\rendering\Render.pas',
  RenderEnvironment in 'source\rendering\RenderEnvironment.pas',
  RenderingMachine in 'source\rendering\RenderingMachine.pas',
  ShaderBank in 'source\rendering\ShaderBank.pas',
  dglOpenGL in 'source\rendering\dglOpenGL.pas',
  NormalsConstants in 'source\constants\NormalsConstants.pas',
  Model in 'source\rendering\Model.pas',
  LOD in 'source\rendering\LOD.pas',
  Material in 'source\rendering\Material.pas',
  Mesh in 'source\rendering\Mesh.pas',
  MeshBRepGeometry in 'source\rendering\MeshBRepGeometry.pas',
  MeshGeometryBase in 'source\rendering\MeshGeometryBase.pas',
  VertexTransformationUtils in 'source\maths\VertexTransformationUtils.pas',
  NormalsMeshPlugin in 'source\rendering\meshplugins\NormalsMeshPlugin.pas',
  BumpMapDataPlugin in 'source\rendering\meshplugins\BumpMapDataPlugin.pas',
  DifferentMeshFaceTypePlugin in 'source\rendering\meshplugins\DifferentMeshFaceTypePlugin.pas',
  MeshPluginBase in 'source\rendering\meshplugins\MeshPluginBase.pas',
  NeighborhoodDataPlugin in 'source\rendering\meshplugins\NeighborhoodDataPlugin.pas',
  BasicFunctions in 'source\utils\BasicFunctions.pas',
  StopWatch in 'source\utils\StopWatch.pas',
  Debug in 'source\utils\Debug.pas',
  GenericThread in 'source\utils\GenericThread.pas',
  Internet in 'source\utils\Internet.pas',
  gifimage in 'source\filetypes\images\gifimage.pas',
  FTGifAnimate in 'source\filetypes\images\FTGifAnimate.pas',
  Histogram in 'source\utils\Histogram.pas',
  ImageIOUtils in 'source\utils\ImageIOUtils.pas',
  SysInfo in 'source\utils\SysInfo.pas',
  NeighborDetector in 'source\utils\NeighborDetector.pas',
  CustomScheme in 'source\control\CustomScheme.pas',
  AutoUpdater in 'source\control\AutoUpdater.pas',
  Mouse in 'source\control\Mouse.pas',
  Voxel_Engine in 'source\control\Voxel_Engine.pas',
  MeshProcessingTool in 'source\control\mesh\MeshProcessingTool.pas',
  MeshColoursTool in 'source\control\mesh\MeshColoursTool.pas',
  MeshNormalsTool in 'source\control\mesh\MeshNormalsTool.pas',
  MeshOptimizationTool in 'source\control\mesh\MeshOptimizationTool.pas',
  MeshGeometryList in 'source\datatypes\advanced\MeshGeometryList.pas',
  TriangleFiller in 'source\control\mesh\TriangleFiller.pas',
  TextureAtlasExtractor in 'source\control\mesh\TextureAtlasExtractor.pas',
  TextureGeneratorBase in 'source\control\mesh\TextureGeneratorBase.pas',
  UI2DEditView in 'source\control\UI2DEditView.pas',
  VoxelUndoEngine in 'source\control\VoxelUndoEngine.pas',
  Voxel_AutoNormals in 'source\control\voxels\Voxel_AutoNormals.pas',
  Voxel_Tools in 'source\control\voxels\Voxel_Tools.pas',
  FillUselessGapsTool in 'source\control\voxels\FillUselessGapsTool.pas',
  VH_SurfaceGen in 'source\control\voxels\VH_SurfaceGen.pas',
  FormSurface in 'source\forms\FormSurface.pas' {FrmSurfaces},
  TopologyFixer in 'source\control\voxels\TopologyFixer.pas',
  TopologyAnalyzer in 'source\control\voxels\TopologyAnalyzer.pas',
  VoxelMeshGenerator in 'source\rendering\VoxelMeshGenerator.pas',
  VolumeFaceVerifier in 'source\utils\VolumeFaceVerifier.pas',
  RefinementTrianglesSupporter in 'source\utils\RefinementTrianglesSupporter.pas',
  ThreeDMap in 'source\utils\ThreeDMap.pas',
  VoxelMap in 'source\utils\VoxelMap.pas',
  VoxelDocumentBank in 'source\document\VoxelDocumentBank.pas',
  HVABank in 'source\document\HVABank.pas',
  HVABankItem in 'source\document\HVABankItem.pas',
  ModelBank in 'source\document\ModelBank.pas',
  ModelBankItem in 'source\document\ModelBankItem.pas',
  VoxelBank in 'source\document\VoxelBank.pas',
  VoxelBankItem in 'source\document\VoxelBankItem.pas',
  VoxelDocument in 'source\document\VoxelDocument.pas',
  HVA in 'source\document\HVA.pas',
  normals in 'source\document\normals.pas',
  Palette in 'source\document\Palette.pas',
  Voxel in 'source\document\Voxel.pas',
  Config in 'source\control\Config.pas',
  Pause in 'source\utils\Pause.pas',
  TextureAtlasExtractorBase in 'source\control\mesh\TextureAtlasExtractorBase.pas',
  TextureAtlasExtractorOrigami in 'source\control\mesh\TextureAtlasExtractorOrigami.pas',
  TextureAtlasExtractorOrigamiGA in 'source\control\mesh\TextureAtlasExtractorOrigamiGA.pas',
  ColisionCheckGA in 'source\maths\geometric_algebra\ColisionCheckGA.pas',
  ModelUndoEngine in 'source\control\ModelUndoEngine.pas',
  ActorActionController in 'source\control\ActorActionController.pas',
  CommandBase in 'source\control\CommandBase.pas',
  ActorActionCommandBase in 'source\control\ActorActionCommandBase.pas',
  TextureAtlasExtractorCommand in 'source\control\commands\TextureAtlasExtractorCommand.pas',
  DiffuseTextureGenerator in 'source\control\mesh\DiffuseTextureGenerator.pas',
  NormalMapTextureGenerator in 'source\control\mesh\NormalMapTextureGenerator.pas',
  BumpMapTextureGenerator in 'source\control\mesh\BumpMapTextureGenerator.pas',
  TextureAtlasExtractorOrigamiCommand in 'source\control\commands\TextureAtlasExtractorOrigamiCommand.pas',
  TextureAtlasExtractorOrigamiGACommand in 'source\control\commands\TextureAtlasExtractorOrigamiGACommand.pas',
  DiffuseTextureGeneratorCommand in 'source\control\commands\DiffuseTextureGeneratorCommand.pas',
  NormalMapTextureGeneratorCommand in 'source\control\commands\NormalMapTextureGeneratorCommand.pas',
  BumpMapTextureGeneratorCommand in 'source\control\commands\BumpMapTextureGeneratorCommand.pas',
  MeshSmoothSBGAMESDraft in 'source\control\mesh\MeshSmoothSBGAMESDraft.pas',
  MeshProcessingBase in 'source\control\mesh\MeshProcessingBase.pas',
  DistanceFormulas in 'source\utils\DistanceFormulas.pas',
  MeshSmoothMasters in 'source\control\mesh\MeshSmoothMasters.pas',
  MeshSmoothSBGAMES in 'source\control\mesh\MeshSmoothSBGAMES.pas',
  MeshSmoothGaussian in 'source\control\mesh\MeshSmoothGaussian.pas',
  MeshUnsharpMasking in 'source\control\mesh\MeshUnsharpMasking.pas',
  MeshInflate in 'source\control\mesh\MeshInflate.pas',
  MeshDeflate in 'source\control\mesh\MeshDeflate.pas',
  MeshCurvatureMeasure in 'source\utils\MeshCurvatureMeasure.pas',
  ColisionCheckBase in 'source\maths\ColisionCheckBase.pas',
  ColisionCheck in 'source\maths\ColisionCheck.pas',
  MeshSmoothSBGamesDraftCommand in 'source\control\commands\MeshSmoothSBGamesDraftCommand.pas',
  MeshSmoothSBGamesCommand in 'source\control\commands\MeshSmoothSBGamesCommand.pas',
  MeshSmoothGaussianCommand in 'source\control\commands\MeshSmoothGaussianCommand.pas',
  MeshSmoothMastersCommand in 'source\control\commands\MeshSmoothMastersCommand.pas',
  MeshUnsharpMaskingCommand in 'source\control\commands\MeshUnsharpMaskingCommand.pas',
  MeshInflateCommand in 'source\control\commands\MeshInflateCommand.pas',
  MeshDeflateCommand in 'source\control\commands\MeshDeflateCommand.pas',
  MeshSmoothVertexNormals in 'source\control\mesh\MeshSmoothVertexNormals.pas',
  MeshSmoothFaceNormals in 'source\control\mesh\MeshSmoothFaceNormals.pas',
  MeshSmoothVertexNormalsCommand in 'source\control\commands\MeshSmoothVertexNormalsCommand.pas',
  MeshSmoothFaceNormalsCommand in 'source\control\commands\MeshSmoothFaceNormalsCommand.pas',
  MeshSmoothVertexColours in 'source\control\mesh\MeshSmoothVertexColours.pas',
  MeshSmoothFaceColours in 'source\control\mesh\MeshSmoothFaceColours.pas',
  MeshSmoothFaceColoursCommand in 'source\control\commands\MeshSmoothFaceColoursCommand.pas',
  MeshSmoothVertexColoursCommand in 'source\control\commands\MeshSmoothVertexColoursCommand.pas',
  ModelLoadCommand in 'source\control\commands\ModelLoadCommand.pas',
  MeshConvertQuadsToTris in 'source\control\mesh\MeshConvertQuadsToTris.pas',
  MeshConvertQuadsTo48Tris in 'source\control\mesh\MeshConvertQuadsTo48Tris.pas',
  MeshConvertQuadsToTrisCommand in 'source\control\commands\MeshConvertQuadsToTrisCommand.pas',
  MeshConvertQuadsTo48TrisCommand in 'source\control\commands\MeshConvertQuadsTo48TrisCommand.pas',
  MeshRecalculateNormals in 'source\control\mesh\MeshRecalculateNormals.pas',
  MeshRecalculateNormalsCommand in 'source\control\commands\MeshRecalculateNormalsCommand.pas',
  MeshSetVertexNormals in 'source\control\mesh\MeshSetVertexNormals.pas',
  MeshSetVertexNormalsCommand in 'source\control\commands\MeshSetVertexNormalsCommand.pas',
  MeshNormalVectorCalculator in 'source\control\mesh\MeshNormalVectorCalculator.pas',
  MeshSetFaceNormals in 'source\control\mesh\MeshSetFaceNormals.pas',
  MeshSetFaceNormalsCommand in 'source\control\commands\MeshSetFaceNormalsCommand.pas',
  MeshSetVertexColours in 'source\control\mesh\MeshSetVertexColours.pas',
  MeshColourCalculator in 'source\control\mesh\MeshColourCalculator.pas',
  MeshSetFaceColours in 'source\control\mesh\MeshSetFaceColours.pas',
  MeshSetVertexColoursCommand in 'source\control\commands\MeshSetVertexColoursCommand.pas',
  MeshSetFaceColoursCommand in 'source\control\commands\MeshSetFaceColoursCommand.pas',
  ModelRebuildCommand in 'source\control\commands\ModelRebuildCommand.pas',
  LODPostProcessing in 'source\control\mesh\LODPostProcessing.pas',
  ModelRebuildLODCommand in 'source\control\commands\ModelRebuildLODCommand.pas',
  BaseController in 'source\control\BaseController.pas',
  ControllerObjectList in 'source\control\ControllerObjectList.pas',
  ControllerObjectItem in 'source\control\ControllerObjectItem.pas',
  ControllerObjectCommandList in 'source\control\ControllerObjectCommandList.pas',
  ControllerObjectCommandItem in 'source\control\ControllerObjectCommandItem.pas',
  ControllerDataTypes in 'source\datatypes\ControllerDataTypes.pas',
  OpenCLLauncher in 'source\utils\OpenCLLauncher.pas',
  oclUtils in 'source\utils\OpenCL\oclUtils.pas',
  CL in 'source\utils\OpenCL\CL.pas',
  cl_platform in 'source\utils\OpenCL\cl_platform.pas',
  cl_ext in 'source\utils\OpenCL\cl_ext.pas',
  clext in 'source\utils\OpenCL\clext.pas',
  TextureAtlasExtractorOrigamiGPU in 'source\control\mesh\TextureAtlasExtractorOrigamiGPU.pas',
  TextureAtlasExtractorOrigamiMT in 'source\control\mesh\TextureAtlasExtractorOrigamiMT.pas',
  DiffuseDebugTextureGenerator in 'source\control\mesh\DiffuseDebugTextureGenerator.pas',
  DiffuseDebugTextureGeneratorCommand in 'source\control\commands\DiffuseDebugTextureGeneratorCommand.pas',
  BasicRenderingTypes in 'source\datatypes\BasicRenderingTypes.pas',
  BasicMathsTypes in 'source\datatypes\BasicMathsTypes.pas',
  BasicVXLSETypes in 'source\datatypes\BasicVXLSETypes.pas',
  MeshOptimization2009 in 'source\control\mesh\MeshOptimization2009.pas',
  MeshOptimization2009Command in 'source\control\commands\MeshOptimization2009Command.pas',
  ModelChangeRemappableCommand in 'source\control\commands\ModelChangeRemappableCommand.pas',
  HierarchyAnimation in 'source\rendering\HierarchyAnimation.pas',
  TransformAnimation in 'source\rendering\TransformAnimation.pas',
  MeshVxt in 'source\rendering\MeshVxt.pas',
  ModelVxt in 'source\rendering\ModelVxt.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'Voxel Section Editor III';
  //  Application.CreateForm(TFrmTimeMain, FrmTimeMain);
  Application.CreateForm(TFrmMain, FrmMain);
  Application.Run;
end.
